import type { CatalogItem, LifeEventKind } from "./types";

// 絞り込みチップとセクションの並び。時系列。
export const LIFE_EVENT_KINDS: readonly {
  kind: LifeEventKind;
  label: string;
}[] = [
  { kind: "preconception", label: "妊活" },
  { kind: "pregnancy", label: "妊娠" },
  { kind: "birth", label: "出産" },
  { kind: "nursery", label: "保育園" },
  { kind: "school", label: "小学校" },
];

// key は項目の意味を表す不変の識別子。title を直しても key は変えない。
// 外した項目の key は再利用しない。
// timing が null の項目は目安日を持たない（基準日から決められないもの）。
export const LIFE_EVENT_CATALOG: readonly CatalogItem[] = [
  {
    key: "preconception:folic-acid",
    kind: "preconception",
    title: "葉酸サプリを飲み始める",
    summary: "妊娠前から飲むよう勧められている栄養素。",
    note: "妊娠の1か月以上前から妊娠3か月までは、食事に加えてサプリで1日400μgとるのが勧められている。",
    aliases: ["葉酸", "サプリメント"],
    timing: null,
    url: null,
  },
  {
    key: "preconception:rubella-antibody-test",
    kind: "preconception",
    title: "風しんの抗体検査を受ける(必要ならワクチン接種)",
    summary: "妊娠中の感染を防ぐため、抗体があるかを調べる。",
    note: "妊娠中は接種できず、接種後は約2か月避妊が必要。自治体で費用の助成があることが多い。パートナーも対象になる。",
    aliases: ["風疹", "抗体検査", "MRワクチン", "麻しん風しん"],
    timing: null,
    url: null,
  },
  {
    key: "preconception:bridal-check",
    kind: "preconception",
    title: "ブライダルチェックを受ける",
    summary: "妊娠に向けて、子宮・卵巣や感染症などを調べる検査。",
    note: "産婦人科で子宮・卵巣の状態や感染症などを確認する。パートナーの検査も合わせて検討する。",
    aliases: ["プレコンセプションケア", "妊活検査"],
    timing: null,
    url: null,
  },
  {
    key: "preconception:visit-clinic-if-not-conceived",
    kind: "preconception",
    title: "不妊検査を受ける",
    summary: "半年〜1年授からないときの受診の目安。",
    note: "避妊をせずに1年授からなければ受診が勧められる。35歳以上は半年が目安。早めの相談で選択肢が広がる。",
    aliases: ["不妊外来", "不妊クリニック"],
    timing: null,
    url: null,
  },
  {
    key: "preconception:check-infertility-subsidy",
    kind: "preconception",
    title: "不妊治療の保険適用と助成を確認する",
    summary: "不妊治療で使える保険と自治体の助成。",
    note: "体外受精などは保険適用になっているが、年齢・回数の条件がある。先進医療などに自治体独自の助成があることも多い。",
    aliases: ["体外受精", "顕微授精", "人工授精", "特定不妊治療", "先進医療"],
    timing: null,
    url: null,
  },
  {
    key: "pregnancy:choose-maternity-clinic",
    kind: "pregnancy",
    title: "産院を決めて分娩予約をする",
    summary: "出産する病院を決めて、分娩の予約を取る。",
    note: "人気の産院は妊娠がわかってすぐ埋まることもある。無痛分娩を考えるなら対応している産院を探す。",
    aliases: ["分娩予約", "病院選び", "無痛分娩"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -240 },
    url: null,
  },
  {
    key: "pregnancy:get-maternal-health-handbook",
    kind: "pregnancy",
    title: "妊娠届を出して母子健康手帳をもらう",
    summary: "市区町村に妊娠を届け出て、母子手帳と健診の受診票を受け取る。",
    note: "産院で妊娠が確かめられたら早めに。妊婦健診の受診票も一緒にもらえ、使うと健診費用の助成を受けられる。",
    aliases: [
      "妊娠届",
      "妊娠届出書",
      "母子手帳",
      "親子健康手帳",
      "妊婦健診",
      "受診票",
    ],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -210 },
    url: null,
  },
  {
    key: "pregnancy:consider-satogaeri-birth",
    kind: "pregnancy",
    title: "里帰り出産をするか決める",
    summary:
      "実家の近くで出産するかどうか。する場合は里帰り先の産院を予約する。",
    note: "里帰り先の分娩予約も早く埋まる。里帰り先では妊婦健診の受診票が使えず、後から払い戻しを申請する自治体が多い。",
    aliases: ["里帰り"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -210 },
    url: null,
  },
  {
    key: "pregnancy:check-pregnancy-support-benefit",
    kind: "pregnancy",
    title: "妊婦のための支援給付を申請する",
    summary: "妊娠中と出生後の2回に分けて受け取れる給付。",
    note: "妊娠届のあとの面談で1回目（5万円）、出生後の面談で2回目（子1人につき5万円）を申請する。",
    aliases: ["出産・子育て応援交付金", "出産応援ギフト", "伴走型相談支援"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -200 },
    url: null,
  },
  {
    key: "pregnancy:inu-no-hi-prayer",
    kind: "pregnancy",
    title: "戌の日の安産祈願をする",
    summary: "妊娠5か月ごろの戌の日に、神社で安産を祈る慣習。",
    note: "日にちは厳密でなくてよい。腹帯を巻く帯祝いを合わせてする家庭も多い。",
    aliases: ["帯祝い", "腹帯", "安産祈願"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -160 },
    url: null,
  },
  {
    key: "pregnancy:talk-leave-with-employer",
    kind: "pregnancy",
    title: "産休・育休を会社に申し出る(妻)",
    summary: "産前・産後休業と育児休業の時期を勤務先に伝える。",
    note: "産前休業は予定日の6週間前（双子以上は14週間前）から取れ、産後8週間は原則働けない。育休は始める1か月前までに申し出る。",
    aliases: ["産前産後休業", "育児休業", "産休", "育休"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -120 },
    url: null,
  },
  {
    key: "pregnancy:parenting-class",
    kind: "pregnancy",
    title: "両親学級に参加する",
    summary: "自治体や産院が開く、出産・育児の準備講座。",
    note: "沐浴の練習や出産の流れを教わる。人気の回は早く埋まるので予約しておく。",
    aliases: ["母親学級", "父親学級", "プレママ教室", "マタニティクラス"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -100 },
    url: null,
  },
  {
    key: "pregnancy:rsv-maternal-vaccine",
    kind: "pregnancy",
    title: "RSウイルス母子免疫ワクチンを接種する",
    summary: "妊婦が接種して、生まれた赤ちゃんをRSウイルスから守る。",
    note: "2026年4月から定期接種（公費）。妊娠28〜36週に1回受ける。妊婦健診で相談する。",
    aliases: ["RSウイルス", "アブリスボ", "母子免疫"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -70 },
    url: null,
  },
  {
    key: "pregnancy:paternity-leave",
    kind: "pregnancy",
    title: "育休を会社に申し出る(夫)",
    summary:
      "出生直後に取れる産後パパ育休と、通常の育休の時期を勤務先に伝える。",
    note: "産後パパ育休は出生後8週間以内に最大4週間、2回まで分けて取れ、申し出は原則2週間前まで。通常の育休は1か月前までに申し出る。",
    aliases: ["産後パパ育休", "出生時育児休業", "育児休業", "育休", "男性育休"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -60 },
    url: null,
  },
  {
    key: "pregnancy:postpartum-care-service",
    kind: "pregnancy",
    title: "産後ケアを申し込む",
    summary: "退院後の母子が助産師などのケアを受けられる自治体の事業。",
    note: "宿泊・日帰り・訪問の形がある。妊娠中に事前の登録が必要な自治体もある。",
    aliases: ["産後ケア事業", "産後ケア"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -60 },
    url: null,
  },
  {
    key: "pregnancy:consider-baby-names",
    kind: "pregnancy",
    title: "名前の候補を決める",
    summary: "出生届までに子の名前を決めておく。",
    note: "出生届（生後14日以内）までに決める。使える漢字は常用漢字と人名用漢字に限られ、名前の読み仮名も届け出る。",
    aliases: ["名付け", "命名"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -45 },
    url: null,
  },
  {
    key: "pregnancy:prepare-baby-goods-car-seat",
    kind: "pregnancy",
    title: "チャイルドシートを用意する",
    summary: "6歳未満を車に乗せるときに使う義務がある座席。",
    note: "退院するとき車で帰るなら、その時から必要。新生児に対応した型を選ぶ。",
    aliases: ["ベビーシート"],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -30 },
    url: null,
  },
  {
    key: "birth:birth-registration",
    kind: "birth",
    title: "出生届を出す",
    summary: "子の誕生を市区町村に届け出る。",
    note: "生まれた日を1日目として数えて14日以内。産院が書く出生証明書と一体の用紙を使う。",
    aliases: ["出生の届出", "出生証明書"],
    timing: { kind: "deadline", anchor: "birth", offsetDays: 13 },
    url: null,
  },
  {
    key: "birth:enroll-health-insurance",
    kind: "birth",
    title: "健康保険の加入手続きをする",
    summary: "子を親の健康保険に入れる。",
    note: "職場の健康保険なら勤務先へ、国民健康保険なら市区町村窓口へ。乳幼児医療証や出産育児一時金の申請に必要になることが多い。",
    aliases: ["扶養", "被扶養者", "国民健康保険", "保険証"],
    timing: { kind: "around", anchor: "birth", offsetDays: 13 },
    url: null,
  },
  {
    key: "birth:apply-childbirth-lump-sum",
    kind: "birth",
    title: "出産育児一時金の手続きをする",
    summary: "出産費用にあてる健康保険の給付。",
    note: "子1人につき50万円（産科医療補償制度に入っていない産院では48.8万円）。多くは産院で直接支払制度を使い、費用が一時金より少なければ差額を健康保険に申請する。",
    aliases: ["出産一時金", "直接支払制度", "受取代理制度"],
    timing: { kind: "around", anchor: "birth", offsetDays: 14 },
    url: null,
  },
  {
    key: "birth:apply-infant-medical-certificate",
    kind: "birth",
    title: "乳幼児医療証を申請する",
    summary: "子の医療費の自己負担を自治体が助成する受給者証。",
    note: "健康保険の加入が済んでから申請する自治体が多い。呼び方は自治体で異なる。",
    aliases: ["子ども医療費助成", "医療証", "マル乳", "乳幼児医療費助成"],
    timing: { kind: "around", anchor: "birth", offsetDays: 14 },
    url: null,
  },
  {
    key: "birth:apply-child-allowance",
    kind: "birth",
    title: "児童手当を申請する",
    summary: "子を育てる家庭に毎月分が支給される手当。",
    note: "出生日の翌日から15日以内に申請する。遅れると、遅れた分の月は受け取れないことがある。",
    aliases: ["認定請求", "子ども手当"],
    timing: { kind: "deadline", anchor: "birth", offsetDays: 15 },
    url: null,
  },
  {
    key: "birth:newborn-home-visit",
    kind: "birth",
    title: "新生児訪問を受ける",
    summary: "保健師や助産師が家に来て、母子の様子を見てくれる。",
    note: "自治体から連絡が来ることが多いが、無ければこちらから問い合わせる。",
    aliases: ["赤ちゃん訪問", "こんにちは赤ちゃん", "乳児家庭全戸訪問"],
    timing: { kind: "around", anchor: "birth", offsetDays: 28 },
    url: null,
  },
  {
    key: "birth:one-month-checkup",
    kind: "birth",
    title: "1か月健診を受ける",
    summary: "生後1か月ごろに受ける、母子それぞれの健診。",
    note: "出産した産院で受けることが多い。",
    aliases: ["一か月健診", "乳児健診"],
    timing: { kind: "around", anchor: "birth", offsetDays: 30 },
    url: null,
  },
  {
    key: "birth:baby-my-number-card",
    kind: "birth",
    title: "子のマイナンバーカードを申請する",
    summary: "病院で保険証として使うカード。",
    note: "出生届のあと、マイナンバーの通知が届いてから申請する。1歳未満は顔写真なしで作れる。",
    aliases: ["マイナンバー", "マイナ保険証"],
    timing: { kind: "around", anchor: "birth", offsetDays: 30 },
    url: null,
  },
  {
    key: "birth:omiyamairi",
    kind: "birth",
    title: "お宮参りに行く",
    summary: "生後1か月ごろ、神社で赤ちゃんの誕生を報告する慣習。",
    note: "地域や家によって時期に幅がある。",
    aliases: ["初宮参り"],
    timing: { kind: "around", anchor: "birth", offsetDays: 31 },
    url: null,
  },
  {
    key: "birth:check-vaccination-schedule",
    kind: "birth",
    title: "生後2か月の予防接種を受ける",
    summary: "生後2か月から始まる定期接種。",
    note: "ヒブ・肺炎球菌・B型肝炎・ロタ・五種混合などを同時に受けることが多い。接種の回数が多いので早めに予約する。",
    aliases: ["ワクチン", "定期接種", "ワクチンデビュー"],
    timing: { kind: "around", anchor: "birth", offsetDays: 60 },
    url: null,
  },
  {
    key: "birth:maternity-allowance",
    kind: "birth",
    title: "出産手当金を申請する(妻)",
    summary: "産休中に給与が出ない分を健康保険が補う給付。",
    note: "勤務先の健康保険に入っている人が対象（国民健康保険にはない）。産後56日を過ぎてから、勤務先を通して申請することが多い。",
    aliases: ["産休手当"],
    timing: { kind: "around", anchor: "birth", offsetDays: 60 },
    url: null,
  },
  {
    key: "birth:okuizome",
    kind: "birth",
    title: "お食い初めをする",
    summary: "生後100日ごろ、一生食べ物に困らないよう願う慣習。",
    note: "数え方に地域差がある。",
    aliases: ["百日祝い", "箸初め", "真魚始め"],
    timing: { kind: "around", anchor: "birth", offsetDays: 100 },
    url: null,
  },
  {
    key: "birth:infant-checkup-3-4-months",
    kind: "birth",
    title: "3〜4か月児健診を受ける",
    summary: "自治体が行う乳児の健診。",
    note: "自治体から案内が届くことが多い。",
    aliases: ["乳児健診", "3か月健診", "4か月健診"],
    timing: { kind: "around", anchor: "birth", offsetDays: 105 },
    url: null,
  },
  {
    key: "birth:first-sekku",
    kind: "birth",
    title: "初節句を祝う",
    summary: "生まれて初めての節句を祝う慣習。",
    note: "女の子は3月3日、男の子は5月5日。生まれて間もない場合は翌年に祝う家庭も多い。日付は決まっているので基準日からの計算はしない。",
    aliases: ["ひな祭り", "桃の節句", "端午の節句", "こどもの日"],
    timing: null,
    url: null,
  },
  {
    key: "birth:first-birthday",
    kind: "birth",
    title: "初誕生を祝う",
    summary: "1歳の誕生日を祝う慣習。",
    note: "一升餅を背負わせる、選び取りをするなどの慣習がある。地域や家によってやり方はさまざま。",
    aliases: ["一升餅", "選び取り", "1歳の誕生日"],
    timing: { kind: "around", anchor: "birth", offsetDays: 365 },
    url: null,
  },
  {
    key: "birth:checkup-18-months",
    kind: "birth",
    title: "1歳6か月児健診を受ける",
    summary: "自治体が行う幼児の健診。",
    note: null,
    aliases: ["1歳半健診"],
    timing: { kind: "around", anchor: "birth", offsetDays: 545 },
    url: null,
  },
  {
    key: "birth:checkup-3-years",
    kind: "birth",
    title: "3歳児健診を受ける",
    summary: "自治体が行う幼児の健診。",
    note: null,
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 1095 },
    url: null,
  },
  {
    key: "nursery:consider-nursery-strategy",
    kind: "nursery",
    title: "保育園の候補を決める",
    summary: "見学して、申し込む園と希望の順位を決める。",
    note: "認可保育所は自治体が点数（指数）で選考する。自分たちの点数と、園ごとの入りやすさを調べておく。",
    aliases: ["保活", "保育園探し", "園見学", "入園指数", "認可外"],
    timing: { kind: "around", anchor: "birth", offsetDays: 150 },
    url: null,
  },
  {
    key: "nursery:apply-nursery",
    kind: "nursery",
    title: "保育園の入園を申し込む",
    summary: "認可保育所などの入園を市区町村に申し込む。",
    note: "申込時期は希望する開始月で大きく変わる。4月入園は前年秋（10〜11月ごろ）が締切のことが多い。勤務先の就労証明書が必要。",
    aliases: ["入所申込", "認可保育所", "4月入園", "就労証明書"],
    timing: null,
    url: null,
  },
  {
    key: "nursery:kindergarten-application",
    kind: "nursery",
    title: "幼稚園の入園願書を出す",
    summary: "幼稚園の入園を園に申し込む。",
    note: "3年保育は満3歳になったあとの4月に入園し、願書は前年の10〜11月ごろに出すことが多い。満3歳児クラスや2年保育もある。",
    aliases: ["幼稚園", "願書", "3年保育", "認定こども園"],
    timing: null,
    url: null,
  },
  {
    key: "school:consider-elementary-school",
    kind: "school",
    title: "小学校の就学先を決める",
    summary: "学区の小学校に通うか、ほかの選択肢を取るか。",
    note: "区域外就学や指定校変更は自治体への申請が要る。私立や国立の受験は準備に時間がかかるため早めに情報を集める。",
    aliases: ["学区", "区域外就学", "指定校変更", "小学校受験"],
    timing: { kind: "around", anchor: "birth", offsetDays: 1800 },
    url: null,
  },
  {
    key: "school:randoseru",
    kind: "school",
    title: "ランドセルを注文する",
    summary: "入学の1年ほど前から選び始める。",
    note: "人気のモデルは年長の春〜夏に売り切れることがある。",
    aliases: ["ラン活"],
    timing: { kind: "around", anchor: "birth", offsetDays: 1900 },
    url: null,
  },
  {
    key: "school:consider-after-school-care",
    kind: "school",
    title: "学童保育に申し込む",
    summary: "放課後に子を預かる施設への申し込み。",
    note: "申し込みは入学前年の秋〜冬が多い。定員を超えると、親の就労状況などで選考される地域もある。",
    aliases: ["学童", "放課後児童クラブ", "児童館"],
    timing: { kind: "around", anchor: "birth", offsetDays: 2190 },
    url: null,
  },
  {
    key: "school:school-entrance-health-check",
    kind: "school",
    title: "就学時健康診断を受ける",
    summary: "入学前年の秋に、入学予定の小学校などで受ける健診。",
    note: "誕生月によって目安の時期は前後する（学年は4月2日生まれ〜翌4月1日生まれで区切られるため）。",
    aliases: ["就学時健診"],
    timing: { kind: "around", anchor: "birth", offsetDays: 2220 },
    url: null,
  },
  {
    key: "school:prepare-elementary-entry",
    kind: "school",
    title: "入学説明会に参加する",
    summary: "入学前に小学校が開く、保護者向けの説明会。",
    note: "1月ごろに入学通知書（就学通知）が届き、説明会の案内がある。誕生月によって目安の時期は前後する。",
    aliases: ["入学通知書", "就学通知", "入学準備"],
    timing: { kind: "around", anchor: "birth", offsetDays: 2250 },
    url: null,
  },
];

export function findCatalogItem(key: string): CatalogItem | undefined {
  return LIFE_EVENT_CATALOG.find((i) => i.key === key);
}
