import type { CatalogItem, LifeEventKind } from "./types";

// 絞り込みチップとセクションの並び。時系列。
export const LIFE_EVENT_KINDS: readonly {
  kind: LifeEventKind;
  label: string;
}[] = [
  { kind: "preconception", label: "妊活" },
  { kind: "pregnancy", label: "妊娠" },
  { kind: "birth", label: "出産" },
  { kind: "nursery", label: "保育園" },
  { kind: "school", label: "小学校" },
];

// key は項目の意味を表す不変の識別子。title を直しても key は変えない。
// timing が null の項目は目安日を持たない（基準日から決められないもの）。
export const LIFE_EVENT_CATALOG: readonly CatalogItem[] = [
  {
    key: "preconception:start-basal-body-temperature",
    kind: "preconception",
    title: "基礎体温の記録をつけ始める",
    summary: "",
    note: "2〜3か月つけると排卵の傾向がつかめる。アプリや基礎体温表を使う。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "preconception:discuss-conception-plan",
    kind: "preconception",
    title: "パートナーと妊活の進め方を話す",
    summary: "",
    note: "いつまで自己流で続けるか、受診に切り替える目安を先に決めておくと動きやすい。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "preconception:rubella-antibody-test",
    kind: "preconception",
    title: "風しんの抗体検査を受ける(必要ならワクチン接種)",
    summary: "",
    note: "妊娠中は接種できず、接種後は約2か月避妊が必要。自治体で費用の助成があることが多い。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "preconception:bridal-check",
    kind: "preconception",
    title: "ブライダルチェック(妊娠に向けた基礎的な検査)を受ける",
    summary: "",
    note: "産婦人科で子宮・卵巣の状態や感染症などを確認する。パートナーの検査も合わせて検討する。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "preconception:check-infertility-subsidy",
    kind: "preconception",
    title: "不妊検査・不妊治療の助成制度を確認する",
    summary: "",
    note: "保険適用に加えて、自治体独自の助成や上乗せがある。対象・回数・年齢の条件を早めに確認する。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "preconception:visit-clinic-if-not-conceived",
    kind: "preconception",
    title: "半年〜1年で授からなければクリニックを受診する",
    summary: "",
    note: "年齢によって目安は変わる(35歳以上は半年が目安とされる)。早めの相談で選択肢が広がる。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "pregnancy:choose-maternity-clinic",
    kind: "pregnancy",
    title: "産院を決める・分娩予約をする",
    summary: "",
    note: "人気の産院は妊娠がわかってすぐ埋まることもある。役所への手続きではないが早めの検討が必要。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -240 },
    url: null,
  },
  {
    key: "pregnancy:get-maternal-health-handbook",
    kind: "pregnancy",
    title: "母子健康手帳をもらう",
    summary: "",
    note: "妊娠が分かったら早めに。妊婦健診の受診票も一緒に受け取る。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -180 },
    url: null,
  },
  {
    key: "pregnancy:consider-satogaeri-birth",
    kind: "pregnancy",
    title: "里帰り出産をするか検討する",
    summary: "",
    note: "する場合は転院時期・里帰り先での健診の受け方も合わせて調整する。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -150 },
    url: null,
  },
  {
    key: "pregnancy:inu-no-hi-prayer",
    kind: "pregnancy",
    title: "戌の日の安産祈願(帯祝い)をする",
    summary: "",
    note: "妊娠5か月ごろの戌の日に安産を祈願する慣習。日にちは厳密でなくてよい。腹帯を用意する家庭も多い。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -140 },
    url: null,
  },
  {
    key: "pregnancy:talk-leave-with-employer",
    kind: "pregnancy",
    title: "産休・育休の取得について会社と相談する",
    summary: "",
    note: "取得時期・期間・引き継ぎについて早めにすり合わせる。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -120 },
    url: null,
  },
  {
    key: "pregnancy:check-pregnancy-support-benefit",
    kind: "pregnancy",
    title: "妊婦のための支援給付を確認する",
    summary: "",
    note: "該当する場合は妊娠中と出生後の2回に分けて給付を受けられる。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -60 },
    url: null,
  },
  {
    key: "pregnancy:consider-baby-names",
    kind: "pregnancy",
    title: "名前の候補を考える",
    summary: "",
    note: "出生届の提出(生後14日以内が目安)までに決める必要がある。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -45 },
    url: null,
  },
  {
    key: "pregnancy:prepare-baby-goods-car-seat",
    kind: "pregnancy",
    title: "ベビー用品・チャイルドシートを準備する",
    summary: "",
    note: "退院時の移動にチャイルドシートが必要。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -30 },
    url: null,
  },
  {
    key: "pregnancy:prenatal-checkups",
    kind: "pregnancy",
    title: "妊婦健診を受ける",
    summary: "",
    note: "母子手帳と一緒にもらう受診票を使うと費用の助成を受けられる。",
    aliases: [],
    timing: { kind: "around", anchor: "expected_birth", offsetDays: -30 },
    url: null,
  },
  {
    key: "birth:birth-registration",
    kind: "birth",
    title: "出生届を出す",
    summary: "",
    note: "生まれた日を1日目として数えて14日以内が目安。",
    aliases: [],
    timing: { kind: "deadline", anchor: "birth", offsetDays: 13 },
    url: null,
  },
  {
    key: "birth:enroll-health-insurance",
    kind: "birth",
    title: "健康保険の加入手続きをする",
    summary: "",
    note: "職場の健康保険なら勤務先へ、国民健康保険なら市区町村窓口へ。乳幼児医療証や出産育児一時金の申請に必要になることが多い。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 13 },
    url: null,
  },
  {
    key: "birth:apply-childbirth-lump-sum",
    kind: "birth",
    title: "出産育児一時金を申請する",
    summary: "",
    note: null,
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 14 },
    url: null,
  },
  {
    key: "birth:apply-infant-medical-certificate",
    kind: "birth",
    title: "乳幼児医療証を申請する",
    summary: "",
    note: null,
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 14 },
    url: null,
  },
  {
    key: "birth:apply-child-allowance",
    kind: "birth",
    title: "児童手当を申請する",
    summary: "",
    note: "申請が遅れると、遅れた分の月は受け取れないことがある。",
    aliases: [],
    timing: { kind: "deadline", anchor: "birth", offsetDays: 15 },
    url: null,
  },
  {
    key: "birth:newborn-home-visit",
    kind: "birth",
    title: "新生児訪問を受ける",
    summary: "",
    note: "自治体から連絡が来ることが多いが、無ければこちらから問い合わせる。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 28 },
    url: null,
  },
  {
    key: "birth:omiyamairi",
    kind: "birth",
    title: "お宮参りに行く",
    summary: "",
    note: "生後1か月ごろ、氏神様に赤ちゃんの誕生を報告する慣習。地域や家によって時期に幅がある。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 31 },
    url: null,
  },
  {
    key: "birth:check-vaccination-schedule",
    kind: "birth",
    title: "予防接種のスケジュールを確認する",
    summary: "",
    note: "定期接種の種類・時期は自治体や医療機関で確認する。生後2か月ごろから始まるものが多い。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 60 },
    url: null,
  },
  {
    key: "birth:okuizome",
    kind: "birth",
    title: "お食い初め(百日祝い)をする",
    summary: "",
    note: "生後100日ごろ、一生食べ物に困らないようにと願う慣習。数え方に地域差がある。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 100 },
    url: null,
  },
  {
    key: "birth:first-sekku",
    kind: "birth",
    title: "初節句を祝う",
    summary: "",
    note: "女の子は3月3日、男の子は5月5日。生まれて間もない場合は翌年に祝う家庭も多い。日付は決まっているので基準日からの計算はしない。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "birth:infant-checkup-3-4-months",
    kind: "birth",
    title: "乳児健診(3〜4か月児健診)を受ける",
    summary: "",
    note: "自治体から案内が届くことが多い。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 120 },
    url: null,
  },
  {
    key: "birth:consider-return-to-work",
    kind: "birth",
    title: "復職のタイミングを考える",
    summary: "",
    note: "保育園の入園可否・ならし保育の期間もふまえて職場と調整する。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 180 },
    url: null,
  },
  {
    key: "birth:consider-education-savings",
    kind: "birth",
    title: "学資保険・教育費の準備を検討する",
    summary: "",
    note: null,
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 200 },
    url: null,
  },
  {
    key: "birth:first-birthday",
    kind: "birth",
    title: "初誕生(1歳の誕生日)を祝う",
    summary: "",
    note: "一升餅を背負わせる、選び取りをするなどの慣習がある。地域や家によってやり方はさまざま。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 365 },
    url: null,
  },
  {
    key: "birth:check-child-allowance-status-report",
    kind: "birth",
    title: "児童手当の現況届が必要か確認する",
    summary: "",
    note: "多くの場合は提出不要だが、自治体から通知が来たら必ず確認する。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 365 },
    url: null,
  },
  {
    key: "birth:checkup-18-months",
    kind: "birth",
    title: "1歳6か月児健診を受ける",
    summary: "",
    note: null,
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 545 },
    url: null,
  },
  {
    key: "birth:checkup-3-years",
    kind: "birth",
    title: "3歳児健診を受ける",
    summary: "",
    note: null,
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 1095 },
    url: null,
  },
  {
    key: "nursery:consider-nursery-strategy",
    kind: "nursery",
    title: "保活の方針を考える(認可保育園・幼稚園など)",
    summary: "",
    note: "希望する園の種類・見学スケジュールを検討する。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 150 },
    url: null,
  },
  {
    key: "nursery:apply-nursery",
    kind: "nursery",
    title: "保育所等の入園を検討・申し込む",
    summary: "",
    note: "申込時期は希望する開始月で大きく変わる。4月入園の認可保育所は前年秋(10〜11月ごろ)が締切のことが多い。",
    aliases: [],
    timing: null,
    url: null,
  },
  {
    key: "school:consider-elementary-school",
    kind: "school",
    title: "小学校の就学先(学区・区域外就学・受験など)を検討する",
    summary: "",
    note: "学区通学以外を考える場合は準備に時間がかかるため早めに情報収集する。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 1800 },
    url: null,
  },
  {
    key: "school:consider-after-school-care",
    kind: "school",
    title: "学童保育(放課後児童クラブ)を利用するか検討する",
    summary: "",
    note: "人気の学童は定員があるため早めの情報収集が必要な地域もある。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 1900 },
    url: null,
  },
  {
    key: "school:school-entrance-health-check",
    kind: "school",
    title: "就学時健康診断を受ける",
    summary: "",
    note: "小学校入学前年の秋ごろが目安。誕生月によって前後する(学年区分は4月2日生まれ〜翌4月1日生まれで決まるため)。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 2100 },
    url: null,
  },
  {
    key: "school:prepare-elementary-entry",
    kind: "school",
    title: "小学校入学の準備をする",
    summary: "",
    note: "就学時健診のあと、就学通知や入学説明会の案内が届く。誕生月によって前後する。",
    aliases: [],
    timing: { kind: "around", anchor: "birth", offsetDays: 2250 },
    url: null,
  },
];

export function findCatalogItem(key: string): CatalogItem | undefined {
  return LIFE_EVENT_CATALOG.find((i) => i.key === key);
}
